global:
  # Slack webhook URL provided via env when running with --config.expand-env
  slack_api_url: ${SLACK_WEBHOOK_URL}

route:
  receiver: notify-all
  group_by: [alertname]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: notify-all
    slack_configs:
      - channel: ${SLACK_CHANNEL:-#alerts}
        send_resolved: true
        title: "[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}"
        text: >-
          {{ range .Alerts }}*{{ .Labels.severity | upper }}* {{ .Annotations.summary }}\n{{ .Annotations.description }}\nLabels: {{ .Labels }}\n{{ end }}
    webhook_configs:
      - url: ${ALERT_WEBHOOK_URL}
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: [alertname]
