apiVersion: 1

deleteDatasources:
  - name: Prometheus
    type: prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
